# Generated by Django 3.2.13 on 2022-04-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=140)),
                ('description', models.CharField(max_length=400)),
                ('goal', models.CharField(choices=[(0, 'No poverty'), (1, 'Zero hunger'), (2, 'Good health and well-being'), (3, 'Quality education'), (4, 'Gender equality'), (5, 'Clean water and sanitation'), (6, 'Affordable and clean energy'), (7, 'Decent work and economic growth'), (8, 'Industry, innovation, and infrastructure'), (9, 'Reduces inequalities'), (10, 'Sustainable cities and communities'), (11, 'Responsible consumption & production'), (12, 'Climate action'), (13, 'Life below water'), (14, 'Life on land'), (15, 'Peace, justice, and strong institutions')], default=0, max_length=2)),
                ('comments', models.ManyToManyField(related_name='about', to='comments.Comment')),
            ],
            options={
                'permissions': [('can_create_a_project', 'As a user I can create an project'), ('can_read_all_the_project', 'As a user I can read all the project'), ('can_update_project', 'As a user I can update a project'), ('can_delete_project', 'As a user I can delete a project')],
            },
        ),
    ]
