# Generated by Django 3.2.13 on 2022-04-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('description', models.CharField(max_length=400)),
                ('language', models.CharField(choices=[('aa', 'Afar'), ('ab', 'Abkhazian'), ('af', 'Afrikaans'), ('ak', 'Akan'), ('sq', 'Albanian'), ('am', 'Amharic'), ('ar', 'Arabic')], default='aa', max_length=2)),
            ],
            options={
                'permissions': [('can_create_an_organization', 'As a user I can create an organization'), ('can_read_all_the_organization', 'As a user I can read all the organization'), ('can_update_organization', 'As a user I can update my organization'), ('can_delete_organization', 'As a user I can delete my organization')],
            },
        ),
    ]
