# Generated by Django 3.2.13 on 2022-04-29 09:46

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('text', models.CharField(max_length=280)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('in_response_to', models.ForeignKey(blank=True, db_column='in_response_to', null=True, on_delete=models.SET(comments.models.get_placeholder_for_deleted_comments), to='comments.comment')),
            ],
            options={
                'permissions': [('can_create_a_comment', 'As a user I can publish a comment'), ('can_read_all_the_comments', 'As a user I can read all the comments'), ('can_update_comments', 'As a user I can update my comments'), ('can_delete_comment', 'As a user I can delete my tweet')],
            },
        ),
    ]
